@extends('layouts.front') 

@section('title', 'Colaboraciones')
@section('content')
<section class="p-y-lg">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
<div class="app-title">
<img src="https://vaslibre.org.ve/img/logo/vaslibre_468_60.png" alt="Valencia/Venezuela Software Libre" class="img-responsive">
   <h2>Políticas de uso:</h2>
</div>
<div class="main-content text-justify">
   <p> Bienvenido(a) a <strong>VaSLibre</strong> a partir de ahora denominado como página o https://<strong>VaSLibre</strong>.org.ve, donde proveemos información sobre nuestros servicios. Usted al ingresar o visitar a nuestro sitio web, indica que a leído y aceptado los términos del uso de nuestro sitio web. Por favor revíselo con detenimiento. Este acuerdo el cual está sujeto a cambios en cualquier momento, y además los cambios son efectivos en el acto de publicación. Le recomendamos que sitúe esta página en su lista de favoritos para que pueda verla con frecuencia o cuando necesites de alguna información sobre cambios y actualizaciones en nuestros términos del acuerdo original.</p>
   <p><strong> 1. Costos/Terminacion:</strong></p>
   <p> Los costos de suscripción (de existir) por el uso y acceso a <strong>VaSLibre</strong> fueron establecidos, expuesto y presentados a usted cuando usted se registro y pueden cambiar con notificación electrónica previa. <strong>VaSLibre</strong> se reserva el derecho a terminar su acceso y uso en cualquier momento con o sin razón.  <strong>VaSLibre</strong>  puede terminar su acción como usuario registrado enviando notificación al correo electrónico que usted indicó durante su suscripción a nuestro servicio, o cualquier otro correo electrónico que usted haya informado a <strong>VaSLibre</strong> durante su acción como usuario registrado. </p>
   <p> Si <strong>VaSLibre</strong> termina su acción como usuario registrado por razones que determinan una violación de su parte a este acuerdo escrito y expuesto, usted NO estará cualificado para un reembolso de los costos y/o dineros sin importar cual sea la cantidad, que esten asociados con dicha acción como usuario registrado.</p>
   <p><strong> 2. Uso con fines comerciales por usuarios y/o visitantes:</strong></p>
   <p>La página, las áreas, el código, cualquier otra area y/o forma del sito de <strong>VaSLibre</strong> es para el uso individual y personal de su acción como usuario registrado solamente, y no pueden ser utilizados en coneción con cualquier fin comercial.</p>
   <p>Organizaciones, compañías, y/o negocios no pueden suscribirse como usuarios y no son permitidos utilizar <strong>VaSLibre</strong> para cualquier propósito incluyendo pero no limitado a: la solicitación comercial, envío de correo electrónico, mercadeo, o utilizar información de los usuarios de  <strong>VaSLibre</strong> en cualquier forma o formato tanto como: electrónico, impreso, mágnetico, video, dígital  cinta, audio o cualquier otra forma comercial, o no legal y/o cualquier utilización no autorizado por escrito por  <strong>VaSLibre</strong>  . </p>
   <p> El uso de  Links (enlaces), y Frames (marcos) no autorizados o cualquier envio, o solicitud no autorizada será investigada y tomaremos y utilizaremos todo los medios y herramientas legales que provee la ley judicial, incluyendo acción civil, mercantil y/o criminal, terminación de acción como usuario registrado, con fines de implantar el peso de lay ley judicial de acuerdo a nuestra discreción en <strong>VaSLibre</strong>.</p>
   <p>Además, con fines de proteger y prevenir que dichas solicitudes sean utilizadas <strong>VaSLibre</strong> tomará acciones tales como pero no limitadas a: limitación de; envío de correo electrónico, mensajes de chat enviados o recibidos por usuarios y filtración electrónica y/o terminación de correo electrónico y mensajes de chat o publicación de comentarios a nuestra discreción.</p>
   <p><strong>3. Derechos de propiedad sobre contenido en <strong>VaSLibre</strong>:</strong></p>
   <p> <strong>VaSLibre</strong> retiene ciertos derechos de propiedad en el código y en algunos de sus servicios. La pagina y/o sitio de  <strong>VaSLibre</strong> contiene material y contenido con derechos de autor, marcas registradas, y otras propiedades intelectiuales de <strong>VaSLibre</strong> y sus asociados y excepto por aquella información que se considere  información de dominio publico, no se puede copiar, publicar, modificar, transmitir,  distribuir, presentar, vender, prestar dichas propiedades sin permiso escrito por parte de <strong>VaSLibre</strong> .</p>
   <p><strong>4. Contenido publicado en el sitio web/CDA:</strong></p>
   <ul>
      <li> A)  <strong>VaSLibre</strong> reclama inmunidad de responsabilidad bajo todo aclanse de la ley y como provee el  Acto de Decencia en comunicaciones ( <em> Communications Decency Act </em> ) por contenido proveído por terceras partes y acción como usuario registrado y nada en este acuerdo pretende ni es intención de  <strong>VaSLibre</strong>  descartar, remover, dar por alto dicha imunidad. Entiende y esta de conforme y deacuerdo con el hecho que  <strong>VaSLibre</strong>  puede a su discreción remover, cualquier contenido, fotografías, mensajes o cualquier otro material que consideramos ser ofensivo, violen el acuerdo y términos de uso, posean copyright, o pudiesen afectar la seguridad, privacidad, derechos, de <strong>VaSLibre</strong> y sus acción como usuario registrados.</li>
      <li> B) Usted en su propia voluntad es y será responsable por el contenido e información que pública, muestra o postea en <strong>VaSLibre</strong> , además el contenido que tranmite a la acción como usuario registrado de  <strong>VaSLibre</strong> .</li>
      <li> C) Cuando postea, muestra, o publica cualquier contenido, escrito, ímagen, video, audio, o cualquier otro formato en <strong>VaSLibre</strong>, usted esta otorgando permiso automáticamente y garantizando que tiene el derecho de otorgar a <strong>VaSLibre</strong> y su acción como usuario registrado, derechos irrevocables, perpetuos, no exclusivos, totalmente libres de pago, y con derechos de autor globales (<em>mundiales</em>) para utilizar, duplicar, publicar, y destribuir dicho contenido incluyendo derechos de publicidad y permisos. Esto es solo aplicable a ímagenes y contenido que usted haya publicado.</li>
      <li> D) <strong>VaSLibre</strong> investigará y tomará acción legal en contra de cualquier entidad o individuo que viola estos términos de uso y declaraciones. Nuestras acciones pudiesen tomar forma de pero no serán limitadas a remover contenido ofensivo y terminación de acción como usuario registrado de dichos violadores de nuestros términos de uso y declaraciones asociadas. 
         Algunos ejemplos sobre lo que pudiésemos considerar contenido ofensivos y/o ilegales son pero no limitados: contenido que hace referencias a racismo, odio, violar alguna patente, o amenaza expresada en contra de cualquier grupo, persona, o entidad. Cualquier persona que insiste en ser una molestia o provoque ser molestia hacia otro miembro o individuo de nuestra web. Cualquier persona de provea información que no es cierta, abusiva, obsena, o que incluye material con derechos de autor de otro o otra entidad por los cuales dichos derechos no han sido otorgado. Cualquier contenido que contiene profanidad, virus, concursos, intercambio, publicidad, o que viole la privacidad de otro usuarios de nuestra web. Cualquiera que solicite u ofrezca contraseñas de cualquier forma. Cualquiera que tome or forme parte de todo tipo de solicitud tanto comercial como ilegal o no autorizada del contenido de <strong>VaSLibre</strong>
      </li>
      <li> E) Solo utilizaras el servicio de <strong>VaSLibre</strong> de una manera consistente con los acuerdos de servicio, términos de Uso, dentro de lo permitido por la ley judicial y regulaciones.</li>
      <li> F) No utilizará tecnología, buscadores de código, o cualquier forma automática o manual para reprocucir, monitoriar, duplicar, nuestras paginas y contenido, formatos, sin nuestro permiso explicito y escrito autorizada por <strong>VaSLibre</strong>.</li>
      <li> G) No puede ejercer, dirigir, solicitor ningún tipo de publicidad con acción como usuario registrado de nuestra web, ni puede vender, ni comprar productos y servicios de usuarios de <strong>VaSLibre</strong>. Esta prohibido enviar cualquier tipo de comunicación en formato de cadena tanto escrito como cualquier otro formato.</li>
      <li> H) Si usted piensa que sus derechos de autor, marca registrada, ha sido duplicada o distribuida en <strong>VaSLibre</strong> y que constituye una violación de sus derechos sobre dicho contenido, debe de informarnos de inmediato y proveer documentos firmados que indican su participación como dueño de dichos derechos de autor, marca registrada, o documentación que le otorga dichos derechos. Dicha información debe ser consistente con el Acto digital de derechos de autor (Digital Millennium Copyright Act (DMCA)). Debe de inclyir una copia de los documentos que describen claramente dichos derechos y especimen de dicho contenido o marca registrada.</li>
   </ul>
   <p> En <strong>VaSLibre</strong> nuestra política es de cumplir con las leyes sobre derechos de autor y marcas registradas y cumplir con todo reglamiento asociado al mismo, Por tanto requerimos toda documentación necesaria y notificaciones para poder ejercer y ayudar al reclamante. Todo los costos asociados con dicho fin serán responsabilidad del reclamante y dichos costos serán facturados adecuadamente al reclamante.</p>
   <p><strong>5. Disputas de usuarios:</strong></p>
   <p><strong>VaSLibre</strong> no solicita ni controlamos la información que proveen los usuarios entre ellos en nuestro sistema. Usted se puede encontrar con información, y contenido que usted considere de naturaleza ofensiva, incorrecta, o engañoosa. Si esto sucede por favor escribanos a soporte y pida que se revise el perfil del miembro. Por favor, utilice buen sentido común cuando este utilizando nuestro portal, usted es  responsible por la forma que usted interactua con otro miembro de nuestra weby debe  utilizar las medidas apropiadas para asegurar su seguridad (No indicar email - claves de acceso - números de telefónos entre otros datos personales). Dado la naturaleza de este sitio es probale que usted tenga una disputa con otro miembro de la web. A través de este acuerdo usted libera a  <strong>VaSLibre</strong>  incluyendo todos sus empleados y ejecutivos, como al personal autorizado de todo reclamacion, demanda legal o civil, daños casusados de todo tipo de naturaleza tantos conocidos como desconocidos resultantes del  uso y voluntad propia de nuestro sito web y webinteractiva. <strong>VaSLibre</strong> se reserva el derecho pero no esta bajo ninguna obligación a monitoriar disputas o desacuerdos enter usuarios registrados.</p>
   <p><strong>6. Privacidad:</strong></p>
   <p> EL uso de <strong>VaSLibre</strong> y/o sus servicios y/o productos son gobernados, y reforzados por nuestra politica de privacidad. Dicha politica de privacidad puede ser cambiada o alterada tal y como amerite, y sera notificado a sus usuarios por de medios eletronicos que usted indicó en su registro con 7 días de anticipación, pudiendo usted removerse o eliminar su acción como usuario registrado en cualquier momento. Basta con enviarnos un email de retiro.</p>
   <p><strong><br/>
      7. Exención de responsabilidad</strong>
   </p>
   <p> <strong>VaSLibre</strong> y sus directores, ejecutivos, gerentes, administradores, agentes, subsidiarias, y empleados no son responsables por infomación y contenido incorrecto o no exacta publicada en la página/sitio o en conexión con el servicio en  <strong>VaSLibre</strong>  causado por usuarios, usuarios o por cualquier equipo o progamación asociada o utilizada en dicho servicio tanto en línea como no en línea. <strong>VaSLibre</strong> no asume responsabilidad por cualquier error, omisión, interrupción, supresión en operación o transmisión, fallo en líneas de cominicación, robo, destrucción, accesso no autorizado, alteración de usuario, y comunicaciones expuestas por la acción como usuario registrado. <strong>VaSLibre</strong> no se hace responsable por problemas o fallos técnicos de cualquier compañía o proveedor de comunicaciones telefónicas o data, servidores y equipo de computo, Sistemas en línea, proveedores de servicios, fallo en programación y/o código de sistemas, o problemas de congestión en líneas y/o en el Internet. O cualquier sito en el web (www) incluyendo daños a usuarios o usuarios y sus equipos de computos como resultado de carga o descarga de contenido, data, o código en conexión con dicha uso y interacción entre sistemas de cómputos en relación con el uso de el servicio de  <strong>VaSLibre</strong>.</p>
   <p> Bajo ninguna circunstancias  <strong>VaSLibre</strong>  se hara responsable por cualquier pérdida, o daño como resultado de el uso de  <strong>VaSLibre</strong>  y/o el servicio, o contenido y/o información publicada o transmitida a los usuarios y usuarios de  <strong>VaSLibre</strong>  El sitio y/o página y servicio es proveído  tal y como es  y  <strong>VaSLibre</strong>  se exonera de cualquier y toda responsabilidad, y no garantiza que sea apta para cuaquier próposito. <strong>VaSLibre</strong>  no puede garantizar y no ejerce promesas prevenientes de su uso servicios y/o productos.</p>
   <p><br/>
      <strong>8. Limitacion de responsabilidad:</strong>
   </p>
   <p> Excepto en jurisdicciones en cuales dichas povisiones son restringidas, (y en dicho evento responsabilidad sera declarada excenta hasta permitida por la ley) en ningún momento o evento  <strong>VaSLibre</strong> será responsable ante usted o su persona y carácter o a cualquier tercera parte o entidad directa o indirecta por daños consecuenciales, ejemplarios, punitivos, incluyendo la perdida de ganancias de  dineros proveniente por el uso de  <strong>VaSLibre</strong>. Además; expresa que esta de acuerdo que NO tomará ni responsabilizarás a <strong>VaSLibre</strong> y que indemnificas a la empresa y todos aquí mencionados de cualquier accion legal, y todo daños por cualquer causa incluyendo información ofensiva, contradictoria, engañosa por  o de otro usuario o miembro de  <strong>VaSLibre</strong>. Además, de haber cualquier tipo de reclamacion relacionada, seria limitada al monto pagado por usted a  <strong>VaSLibre</strong> durante y limitado al término de su acción como usuario registrado con  <strong>VaSLibre</strong>.</p>
   <p><br/>
      <strong>9. Contenido de usuarios</strong>
   </p>
   <p> Información protegida por los Derechos de Propiedad Intelectual</p>
   <p> La información que aparece en <strong>VaSLibre</strong>, está disponible para que la vea cualquier persona; pero no necesariamente está allí para que sea descargada o usada. Las personas que entren a  <strong>VaSLibre</strong> tienen la posibilidad de copiar electrónicamente, o bien imprimir, secciones de <strong>VaSLibre</strong> para su uso personal y sin fines de lucro. Por lo general está prohibido cualquier otro uso incluyendo, pero sin limitarse a, la reproducción, modificación, distribución, transmisión,  publicación, exhibición o comercialización del contenido de los sitios web.</p>
   <p><br/>
      <strong>10. Jurisdicción legal:</strong>
   </p>
   <p> Cualquier tipo de disputa y/o querella legal relativa al uso de este sitio web, serán interpretados con arreglo a la legislación y jurisdicción de Venezuela y tomando como domicilio fiscal a la Ciudad de Valencia - Carabobo - Venezuela.</p>
   <p><br/>
      <strong>11. Notificaciones:</strong>
   </p>
   Todo contacto ante y para <strong>VaSLibre</strong> será através del formulario de contacto que esta en nuestro sitio web. Cualquier contacto telefónico sin nuestro consentimiento será bajo su responsabilidad  y no aplicamos responsabilidad alguna por información que usted suministre via telefónica o cualquier otro medio que no sea a través de nuestro formulario de contacto.
   <p><br/>
      <strong> 12. Usuarios Registrados</strong>
   </p>
   La informació suministrada por los usuarios registrados esta amparada y protegida bajo las normas internacionales de datos.
   <p>  <strong>VaSLibre</strong>  podrá notificar a las direcciones declaradas por usted durante el processo de registro. Declara y expone que esta de acuerdo y conforme con este y todos los acuerdos y reglamentos expuestos por <strong>VaSLibre</strong> incluyendo la politica de privacidad. Referencias a <strong>VaSLibre</strong> incluyen todo su personal. Si por cualquier razón alguna parte de este acuerdo fuese declarado invalido, las partes subsiguientes se mantredran en efecto.</p>
   <p><strong>VaSLibre</strong> ha elaborado esta declaración sobre la privacidad de los datos para corroborar el compromiso con la protección de la privacidad de sus usuarios y usuarios. EN NINGÚN SUPUESTO <strong>VaSLibre</strong> DARÁ A CONOCER A NINGÚN TERCERO INFORMACIÓN QUE IDENTIFIQUE A SUS USUARIOS INDIVIDUALMENTE, SIN UNA AUTORIZACIÓN EXPRESA DEL USUARIO.</p>
   <p><br/>
      <strong> DATOS PERSONALES</strong>
   </p>
   <p> <strong>VaSLibre</strong> trabaja con datos personales de usuarios a la hora del alta en nuestro sitio web. En el momento del alta, la baja y la modificación de los datos, <strong>VaSLibre</strong> solicita el nombre del usuario y su dirección de correo electrónico; y puede llegar a pedir información adicional que en cualquier caso es otorgada por el usuario en foma voluntaria.</p>
   <p><br/>
      <strong> COOKIES</strong>
   </p>
   <p><strong>VaSLibre</strong> utiliza cookies con valores cifrados y sesiones en todo su web, solo para fines de Usuarios registrados, la cual no contiene datos relevantes del usuario. Solo es usado para información de mercadeo interna de <strong>VaSLibre</strong> .</p>
   <p>Igualmente se emplean servicios de terceros como por ejemplo Google Adsense y Google Analytics, no poseyendo nosotros control sobre el tipo de información que esos servicios realicen con la data recabada.<br/>
   <p>Si desea puede visitar <a href="https://www.google.co.ve/intl/es-419/policies/privacy/" title="Visitar las politicas de uso de Google">https://www.google.co.ve/intl/es-419/policies/privacy/</a> para mayor información.</p>
   <p><br/>
      <strong> DIRECCIONES IP</strong>
   </p>
   <p><strong>VaSLibre</strong> registra las direcciones IP ( de todo lector/navegante/internauta/usuario que visita el sitio) para fines exclusivamente internos, tales como estadísticas de acceso. En ningún caso se darán a conocer a terceros o se utilizarán para revelar datos personales. A menos que sea solicitado por orden legal de la jurisdicción competente.</p>
   <p><br/>
      <strong> Contenido de la web y enlaces (links). </strong>
   </p>
   <p>  <strong>VaSLibre</strong>  Rechaza toda la posible responsabilidad que se derive del mal uso que se realice de los contenidos de la página web, siendo responsabilidad única y exclusivamente del /lector/navegante/internauta/usuario/miembro que accede a ellos o los utilice. Asimismo, no asumimos ninguna otra responsabilidad por la información contenida en el sitio web de terceros a las que se pueda acceder por enlaces o buscadores desde las páginas web de <strong>VaSLibre</strong>. La función de los enlaces que aparecen en este sitio web tiene como única finalidad la informativa y en ningún caso suponen que nosotros sugerimos, invitemos, recomendemos o compartamos sus contenidos, acciones u opiniones. </p>
   <p><strong>VaSLibre</strong> excluye toda garantía implícita o explícita, incluidas las de idoneidad para un fin genérico o específico, competencia profesional y ausencia de infracciones.</p>
   <p> El usuario se abstendrá de utilizar cualquiera de los servicios ofrecidos en esta Web con fines, causas o efectos ilícitos, prohibidos en el presente Aviso, lesivos de los derechos e intereses de terceros, o que puedan dañar, inutilizar, sobrecargar, deteriorar o impedir la normal utilización de los servicios, los equipos informáticos o los documentos, archivos y cualquier contenido almacenado en esta Web.</p>
   <p><strong>VaSLibre</strong> no se responsabiliza del uso ajeno a su voluntad que se produzca en las informaciones aquí expuestas. Todos los datos que aquí figuran lo son a titulo informativo por lo que carecen de cualquier valor probatorio, <strong>VaSLibre</strong> declina toda responsabilidad sobre el uso que se haga de las informaciones y datos aquí expuestos.</p>
   <p> Los usuarios registrados son los únicos responsables de la información que publican en su perfil o entre mensajes de email o chat.</p>
   <p><strong>VaSLibre</strong> se reserva el derecho de modificar su política de seguridad y protección de datos de forma discrecional, en cualquier momento y sin previo aviso, siempre con arreglo y validez a la legislación internacional vigente en materia de protección de datos, con efectos desde la fecha de publicación en  <strong>VaSLibre</strong>.</p>
   <p> <strong>VaSLibre</strong>  no garantiza la licitud, fiabilidad exactitud, exhaustividad, actualidad y utilidad de los contenidos expuesto en su sitio web.</p>
   <p> Las marcas comerciales junto con sus logos y nombres de productos son propiedad intelectual de sus respectivos dueños y/o fabricantes; sin que pueda entenderse que el uso o acceso atribuya al usuario derecho alguno sobre las citadas marcas, nombres comerciales y/o signos distintivo.</p>
   <p> Cuando <strong>VaSLibre</strong> recibe datos de sus Visitantes/usuarios/usuarios por encuestas, compras, participación en sorteos o cualquier otro evento, es porque Usted lo ha entendido así y lo hace voluntariamente. <strong>VaSLibre</strong> garantiza que los datos recibidos serán utilizados solamente para los fines que fueron requeridos.</p>
   <p> Cualquiera puede poner un vínculo hacia  <strong>VaSLibre</strong>  en su sitio web o blog  sin que esto implique recibir un vínculo recíproco. Cualquiera que acceda mediante un vínculo de este tipo queda sujeto por completo a los presentes Términos y Condiciones de Uso.</p>
</div>
            </div>
            {{--  <div class="col-md-4">
                @include('front.partials.widgets.widgets')
            </div>  --}}
        </div>
    </div>
</section>
@endsection